// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ksvc_keyserveservice.proto
#ifndef GRPC_ksvc_5fkeyserveservice_2eproto__INCLUDED
#define GRPC_ksvc_5fkeyserveservice_2eproto__INCLUDED

#include "ksvc_keyserveservice.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace MvdS {
namespace ksvc {

class KeyserveService final {
 public:
  static constexpr char const* service_full_name() {
    return "MvdS.ksvc.KeyserveService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::MvdS::ksvc::KeyRing* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::KeyRing>> AsyncCreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::KeyRing>>(AsyncCreateKeyRingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::KeyRing>> PrepareAsyncCreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::KeyRing>>(PrepareAsyncCreateKeyRingRaw(context, request, cq));
    }
    virtual ::grpc::Status CreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::MvdS::ksvc::CryptoKey* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::CryptoKey>> AsyncCreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::CryptoKey>>(AsyncCreateCryptoKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::CryptoKey>> PrepareAsyncCreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::CryptoKey>>(PrepareAsyncCreateCryptoKeyRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void CreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateKeyRing(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MvdS::ksvc::KeyRing* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void CreateKeyRing(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MvdS::ksvc::KeyRing* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void CreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateCryptoKey(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MvdS::ksvc::CryptoKey* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void CreateCryptoKey(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MvdS::ksvc::CryptoKey* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::KeyRing>* AsyncCreateKeyRingRaw(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::KeyRing>* PrepareAsyncCreateKeyRingRaw(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::CryptoKey>* AsyncCreateCryptoKeyRaw(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MvdS::ksvc::CryptoKey>* PrepareAsyncCreateCryptoKeyRaw(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status CreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::MvdS::ksvc::KeyRing* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::KeyRing>> AsyncCreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::KeyRing>>(AsyncCreateKeyRingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::KeyRing>> PrepareAsyncCreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::KeyRing>>(PrepareAsyncCreateKeyRingRaw(context, request, cq));
    }
    ::grpc::Status CreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::MvdS::ksvc::CryptoKey* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::CryptoKey>> AsyncCreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::CryptoKey>>(AsyncCreateCryptoKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::CryptoKey>> PrepareAsyncCreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::CryptoKey>>(PrepareAsyncCreateCryptoKeyRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void CreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response, std::function<void(::grpc::Status)>) override;
      void CreateKeyRing(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MvdS::ksvc::KeyRing* response, std::function<void(::grpc::Status)>) override;
      void CreateKeyRing(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void CreateKeyRing(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MvdS::ksvc::KeyRing* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void CreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response, std::function<void(::grpc::Status)>) override;
      void CreateCryptoKey(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MvdS::ksvc::CryptoKey* response, std::function<void(::grpc::Status)>) override;
      void CreateCryptoKey(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void CreateCryptoKey(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MvdS::ksvc::CryptoKey* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::KeyRing>* AsyncCreateKeyRingRaw(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::KeyRing>* PrepareAsyncCreateKeyRingRaw(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateKeyRingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::CryptoKey>* AsyncCreateCryptoKeyRaw(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MvdS::ksvc::CryptoKey>* PrepareAsyncCreateCryptoKeyRaw(::grpc::ClientContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateKeyRing_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateCryptoKey_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateKeyRing(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response);
    virtual ::grpc::Status CreateCryptoKey(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateKeyRing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CreateKeyRing() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateKeyRing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateKeyRing(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateKeyRing(::grpc::ServerContext* context, ::MvdS::ksvc::CreateKeyRingRequest* request, ::grpc::ServerAsyncResponseWriter< ::MvdS::ksvc::KeyRing>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateCryptoKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CreateCryptoKey() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CreateCryptoKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCryptoKey(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateCryptoKey(::grpc::ServerContext* context, ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::grpc::ServerAsyncResponseWriter< ::MvdS::ksvc::CryptoKey>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateKeyRing<WithAsyncMethod_CreateCryptoKey<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CreateKeyRing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_CreateKeyRing() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::MvdS::ksvc::CreateKeyRingRequest, ::MvdS::ksvc::KeyRing>(
          [this](::grpc::ServerContext* context,
                 const ::MvdS::ksvc::CreateKeyRingRequest* request,
                 ::MvdS::ksvc::KeyRing* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->CreateKeyRing(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_CreateKeyRing(
        ::grpc::experimental::MessageAllocator< ::MvdS::ksvc::CreateKeyRingRequest, ::MvdS::ksvc::KeyRing>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MvdS::ksvc::CreateKeyRingRequest, ::MvdS::ksvc::KeyRing>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CreateKeyRing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateKeyRing(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void CreateKeyRing(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CreateCryptoKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_CreateCryptoKey() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::MvdS::ksvc::CreateCryptoKeyRequest, ::MvdS::ksvc::CryptoKey>(
          [this](::grpc::ServerContext* context,
                 const ::MvdS::ksvc::CreateCryptoKeyRequest* request,
                 ::MvdS::ksvc::CryptoKey* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->CreateCryptoKey(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_CreateCryptoKey(
        ::grpc::experimental::MessageAllocator< ::MvdS::ksvc::CreateCryptoKeyRequest, ::MvdS::ksvc::CryptoKey>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MvdS::ksvc::CreateCryptoKeyRequest, ::MvdS::ksvc::CryptoKey>*>(
          ::grpc::Service::experimental().GetHandler(1))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CreateCryptoKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCryptoKey(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void CreateCryptoKey(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_CreateKeyRing<ExperimentalWithCallbackMethod_CreateCryptoKey<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateKeyRing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CreateKeyRing() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateKeyRing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateKeyRing(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateCryptoKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CreateCryptoKey() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CreateCryptoKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCryptoKey(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateKeyRing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_CreateKeyRing() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateKeyRing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateKeyRing(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateKeyRing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateCryptoKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_CreateCryptoKey() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CreateCryptoKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCryptoKey(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateCryptoKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CreateKeyRing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_CreateKeyRing() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->CreateKeyRing(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_CreateKeyRing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateKeyRing(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void CreateKeyRing(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CreateCryptoKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_CreateCryptoKey() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->CreateCryptoKey(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_CreateCryptoKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCryptoKey(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void CreateCryptoKey(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateKeyRing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CreateKeyRing() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::MvdS::ksvc::CreateKeyRingRequest, ::MvdS::ksvc::KeyRing>(std::bind(&WithStreamedUnaryMethod_CreateKeyRing<BaseClass>::StreamedCreateKeyRing, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CreateKeyRing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateKeyRing(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateKeyRingRequest* request, ::MvdS::ksvc::KeyRing* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateKeyRing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MvdS::ksvc::CreateKeyRingRequest,::MvdS::ksvc::KeyRing>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateCryptoKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CreateCryptoKey() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::MvdS::ksvc::CreateCryptoKeyRequest, ::MvdS::ksvc::CryptoKey>(std::bind(&WithStreamedUnaryMethod_CreateCryptoKey<BaseClass>::StreamedCreateCryptoKey, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CreateCryptoKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateCryptoKey(::grpc::ServerContext* context, const ::MvdS::ksvc::CreateCryptoKeyRequest* request, ::MvdS::ksvc::CryptoKey* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateCryptoKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MvdS::ksvc::CreateCryptoKeyRequest,::MvdS::ksvc::CryptoKey>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateKeyRing<WithStreamedUnaryMethod_CreateCryptoKey<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateKeyRing<WithStreamedUnaryMethod_CreateCryptoKey<Service > > StreamedService;
};

}  // namespace ksvc
}  // namespace MvdS


#endif  // GRPC_ksvc_5fkeyserveservice_2eproto__INCLUDED
