// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ksvc_cryptokeyversion.proto

#ifndef PROTOBUF_INCLUDED_ksvc_5fcryptokeyversion_2eproto
#define PROTOBUF_INCLUDED_ksvc_5fcryptokeyversion_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ksvc_5fcryptokeyversion_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ksvc_5fcryptokeyversion_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ksvc_5fcryptokeyversion_2eproto();
namespace MvdS {
namespace ksvc {
class CryptoKeyVersion;
class CryptoKeyVersionDefaultTypeInternal;
extern CryptoKeyVersionDefaultTypeInternal _CryptoKeyVersion_default_instance_;
}  // namespace ksvc
}  // namespace MvdS
namespace google {
namespace protobuf {
template<> ::MvdS::ksvc::CryptoKeyVersion* Arena::CreateMaybeMessage<::MvdS::ksvc::CryptoKeyVersion>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace MvdS {
namespace ksvc {

// ===================================================================

class CryptoKeyVersion final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MvdS.ksvc.CryptoKeyVersion) */ {
 public:
  CryptoKeyVersion();
  virtual ~CryptoKeyVersion();

  CryptoKeyVersion(const CryptoKeyVersion& from);

  inline CryptoKeyVersion& operator=(const CryptoKeyVersion& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CryptoKeyVersion(CryptoKeyVersion&& from) noexcept
    : CryptoKeyVersion() {
    *this = ::std::move(from);
  }

  inline CryptoKeyVersion& operator=(CryptoKeyVersion&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CryptoKeyVersion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CryptoKeyVersion* internal_default_instance() {
    return reinterpret_cast<const CryptoKeyVersion*>(
               &_CryptoKeyVersion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CryptoKeyVersion* other);
  friend void swap(CryptoKeyVersion& a, CryptoKeyVersion& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CryptoKeyVersion* New() const final {
    return CreateMaybeMessage<CryptoKeyVersion>(nullptr);
  }

  CryptoKeyVersion* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CryptoKeyVersion>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CryptoKeyVersion& from);
  void MergeFrom(const CryptoKeyVersion& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CryptoKeyVersion* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:MvdS.ksvc.CryptoKeyVersion)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ksvc_5fcryptokeyversion_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CryptoKeyVersion

// string name = 1;
inline void CryptoKeyVersion::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CryptoKeyVersion::name() const {
  // @@protoc_insertion_point(field_get:MvdS.ksvc.CryptoKeyVersion.name)
  return name_.GetNoArena();
}
inline void CryptoKeyVersion::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MvdS.ksvc.CryptoKeyVersion.name)
}
#if LANG_CXX11
inline void CryptoKeyVersion::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MvdS.ksvc.CryptoKeyVersion.name)
}
#endif
inline void CryptoKeyVersion::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MvdS.ksvc.CryptoKeyVersion.name)
}
inline void CryptoKeyVersion::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MvdS.ksvc.CryptoKeyVersion.name)
}
inline ::std::string* CryptoKeyVersion::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:MvdS.ksvc.CryptoKeyVersion.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CryptoKeyVersion::release_name() {
  // @@protoc_insertion_point(field_release:MvdS.ksvc.CryptoKeyVersion.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CryptoKeyVersion::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:MvdS.ksvc.CryptoKeyVersion.name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ksvc
}  // namespace MvdS

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ksvc_5fcryptokeyversion_2eproto
