// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ksvc_cryptokeyversiontemplate.proto

#include "ksvc_cryptokeyversiontemplate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace MvdS {
namespace ksvc {
class CryptoKeyVersionTemplateDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CryptoKeyVersionTemplate> _instance;
} _CryptoKeyVersionTemplate_default_instance_;
}  // namespace ksvc
}  // namespace MvdS
static void InitDefaultsCryptoKeyVersionTemplate_ksvc_5fcryptokeyversiontemplate_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MvdS::ksvc::_CryptoKeyVersionTemplate_default_instance_;
    new (ptr) ::MvdS::ksvc::CryptoKeyVersionTemplate();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MvdS::ksvc::CryptoKeyVersionTemplate::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CryptoKeyVersionTemplate_ksvc_5fcryptokeyversiontemplate_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCryptoKeyVersionTemplate_ksvc_5fcryptokeyversiontemplate_2eproto}, {}};

void InitDefaults_ksvc_5fcryptokeyversiontemplate_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_CryptoKeyVersionTemplate_ksvc_5fcryptokeyversiontemplate_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_ksvc_5fcryptokeyversiontemplate_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_ksvc_5fcryptokeyversiontemplate_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_ksvc_5fcryptokeyversiontemplate_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_ksvc_5fcryptokeyversiontemplate_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MvdS::ksvc::CryptoKeyVersionTemplate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MvdS::ksvc::CryptoKeyVersionTemplate, algorithm_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MvdS::ksvc::CryptoKeyVersionTemplate)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::MvdS::ksvc::_CryptoKeyVersionTemplate_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_ksvc_5fcryptokeyversiontemplate_2eproto = {
  {}, AddDescriptors_ksvc_5fcryptokeyversiontemplate_2eproto, "ksvc_cryptokeyversiontemplate.proto", schemas,
  file_default_instances, TableStruct_ksvc_5fcryptokeyversiontemplate_2eproto::offsets,
  file_level_metadata_ksvc_5fcryptokeyversiontemplate_2eproto, 1, file_level_enum_descriptors_ksvc_5fcryptokeyversiontemplate_2eproto, file_level_service_descriptors_ksvc_5fcryptokeyversiontemplate_2eproto,
};

const char descriptor_table_protodef_ksvc_5fcryptokeyversiontemplate_2eproto[] =
  "\n#ksvc_cryptokeyversiontemplate.proto\022\tM"
  "vdS.ksvc\032$ksvc_cryptokeyversionalgorithm"
  ".proto\"S\n\030CryptoKeyVersionTemplate\0227\n\tal"
  "gorithm\030\001 \001(\0162$.MvdS.ksvc.CryptoKeyVersi"
  "onAlgorithmb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_ksvc_5fcryptokeyversiontemplate_2eproto = {
  false, InitDefaults_ksvc_5fcryptokeyversiontemplate_2eproto, 
  descriptor_table_protodef_ksvc_5fcryptokeyversiontemplate_2eproto,
  "ksvc_cryptokeyversiontemplate.proto", &assign_descriptors_table_ksvc_5fcryptokeyversiontemplate_2eproto, 179,
};

void AddDescriptors_ksvc_5fcryptokeyversiontemplate_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_ksvc_5fcryptokeyversionalgorithm_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_ksvc_5fcryptokeyversiontemplate_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ksvc_5fcryptokeyversiontemplate_2eproto = []() { AddDescriptors_ksvc_5fcryptokeyversiontemplate_2eproto(); return true; }();
namespace MvdS {
namespace ksvc {

// ===================================================================

void CryptoKeyVersionTemplate::InitAsDefaultInstance() {
}
class CryptoKeyVersionTemplate::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CryptoKeyVersionTemplate::kAlgorithmFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CryptoKeyVersionTemplate::CryptoKeyVersionTemplate()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MvdS.ksvc.CryptoKeyVersionTemplate)
}
CryptoKeyVersionTemplate::CryptoKeyVersionTemplate(const CryptoKeyVersionTemplate& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  algorithm_ = from.algorithm_;
  // @@protoc_insertion_point(copy_constructor:MvdS.ksvc.CryptoKeyVersionTemplate)
}

void CryptoKeyVersionTemplate::SharedCtor() {
  algorithm_ = 0;
}

CryptoKeyVersionTemplate::~CryptoKeyVersionTemplate() {
  // @@protoc_insertion_point(destructor:MvdS.ksvc.CryptoKeyVersionTemplate)
  SharedDtor();
}

void CryptoKeyVersionTemplate::SharedDtor() {
}

void CryptoKeyVersionTemplate::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CryptoKeyVersionTemplate& CryptoKeyVersionTemplate::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_CryptoKeyVersionTemplate_ksvc_5fcryptokeyversiontemplate_2eproto.base);
  return *internal_default_instance();
}


void CryptoKeyVersionTemplate::Clear() {
// @@protoc_insertion_point(message_clear_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  algorithm_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CryptoKeyVersionTemplate::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<CryptoKeyVersionTemplate*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .MvdS.ksvc.CryptoKeyVersionAlgorithm algorithm = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        ::google::protobuf::uint64 val = ::google::protobuf::internal::ReadVarint(&ptr);
        msg->set_algorithm(static_cast<::MvdS::ksvc::CryptoKeyVersionAlgorithm>(val));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CryptoKeyVersionTemplate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .MvdS.ksvc.CryptoKeyVersionAlgorithm algorithm = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_algorithm(static_cast< ::MvdS::ksvc::CryptoKeyVersionAlgorithm >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MvdS.ksvc.CryptoKeyVersionTemplate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MvdS.ksvc.CryptoKeyVersionTemplate)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CryptoKeyVersionTemplate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MvdS.ksvc.CryptoKeyVersionAlgorithm algorithm = 1;
  if (this->algorithm() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->algorithm(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MvdS.ksvc.CryptoKeyVersionTemplate)
}

::google::protobuf::uint8* CryptoKeyVersionTemplate::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MvdS.ksvc.CryptoKeyVersionAlgorithm algorithm = 1;
  if (this->algorithm() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->algorithm(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MvdS.ksvc.CryptoKeyVersionTemplate)
  return target;
}

size_t CryptoKeyVersionTemplate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .MvdS.ksvc.CryptoKeyVersionAlgorithm algorithm = 1;
  if (this->algorithm() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->algorithm());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CryptoKeyVersionTemplate::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  GOOGLE_DCHECK_NE(&from, this);
  const CryptoKeyVersionTemplate* source =
      ::google::protobuf::DynamicCastToGenerated<CryptoKeyVersionTemplate>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MvdS.ksvc.CryptoKeyVersionTemplate)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MvdS.ksvc.CryptoKeyVersionTemplate)
    MergeFrom(*source);
  }
}

void CryptoKeyVersionTemplate::MergeFrom(const CryptoKeyVersionTemplate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.algorithm() != 0) {
    set_algorithm(from.algorithm());
  }
}

void CryptoKeyVersionTemplate::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CryptoKeyVersionTemplate::CopyFrom(const CryptoKeyVersionTemplate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MvdS.ksvc.CryptoKeyVersionTemplate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CryptoKeyVersionTemplate::IsInitialized() const {
  return true;
}

void CryptoKeyVersionTemplate::Swap(CryptoKeyVersionTemplate* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CryptoKeyVersionTemplate::InternalSwap(CryptoKeyVersionTemplate* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(algorithm_, other->algorithm_);
}

::google::protobuf::Metadata CryptoKeyVersionTemplate::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_ksvc_5fcryptokeyversiontemplate_2eproto);
  return ::file_level_metadata_ksvc_5fcryptokeyversiontemplate_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ksvc
}  // namespace MvdS
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::MvdS::ksvc::CryptoKeyVersionTemplate* Arena::CreateMaybeMessage< ::MvdS::ksvc::CryptoKeyVersionTemplate >(Arena* arena) {
  return Arena::CreateInternal< ::MvdS::ksvc::CryptoKeyVersionTemplate >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
